### ISSUE TITLE
ResizeGrip的样式无法修改

### ISSUE THREAD

**Issue by tpxxn** [tpxxn/JiHuangBaiKeCSharp#2]

**Comment by tpxxn** [comment]
光标样式修改无效

**Comment by lindexi** [comment]
UWP下是不分光标，光标好像不能修改，WPF修改就简单

**Comment by tpxxn** [comment]
可是我这里不管怎么改都没用...

**Comment by lindexi** [comment]
WPF修改很简单

**Comment by tpxxn** [comment]
可是就是没用呀...

**Comment by tpxxn** [comment]
其他的光标都能改，就这个ResizeGrip的光标改不了

**Comment by lindexi** [comment]
我找下博客

**Comment by lindexi** [comment]
http://www.cnblogs.com/TianFang/p/5186497.html

**Comment by tpxxn** [comment]
不是...我的意思是，其他无论什么控件都很容易通过Cursor和资源字典来设置光标样式，但是这个ResizeGrip控件它很犟，就是改不了....

**Comment by lindexi** [comment]
http://www.cnblogs.com/bdstjk/archive/2013/05/11/3072523.html

http://www.cnblogs.com/scy251147/archive/2012/07/25/2609126.html

**Comment by lindexi** [comment]
https://msdn.microsoft.com/zh-cn/library/system.windows.controls.primitives.resizegrip.aspx
Cursor是有的，也就是你的设置理论就是有用，我看下代码

**Comment by lindexi** [comment]
http://stackoverflow.com/questions/3613328/modifying-the-cursor-of-a-resize-grip-in-a-wpf-window-canresizewithgrip-wi

**Comment by tpxxn** [comment]
准确地来说是不知道应该在哪里修改ResizeGrip的样式，各种地方都试了却没有用

**Comment by tpxxn** [comment]
<Style x:Key="WindowStyle" TargetType="{x:Type Window}">
        <Setter Property="Foreground" Value="{DynamicResource {x:Static SystemColors.WindowTextBrushKey}}"/>
        <Setter Property="Background" Value="{DynamicResource {x:Static SystemColors.WindowBrushKey}}"/>
        <Setter Property="Template">
            <Setter.Value>
                <ControlTemplate TargetType="{x:Type Window}">
                    <Border BorderBrush="{TemplateBinding BorderBrush}" BorderThickness="{TemplateBinding BorderThickness}" Background="{TemplateBinding Background}">
                        <Grid>
                            <AdornerDecorator>
                                <ContentPresenter ContentTemplate="{TemplateBinding ContentTemplate}" Content="{TemplateBinding Content}" ContentStringFormat="{TemplateBinding ContentStringFormat}"/>
                            </AdornerDecorator>
                            <ResizeGrip Cursor="Cross" x:Name="WindowResizeGrip" HorizontalAlignment="Right" IsTabStop="False" Visibility="Visible" VerticalAlignment="Bottom" Margin="0,0,2,2">
                                <ResizeGrip.Template>
                                    <ControlTemplate TargetType="{x:Type ResizeGrip}">
                                        <Grid Background="{TemplateBinding Background}" SnapsToDevicePixels="True">
                                            <Path Data="M9,0L11,0 11,11 0,11 0,9 3,9 3,6 6,6 6,3 9,3z" HorizontalAlignment="Right" Margin="0,0,2,2" VerticalAlignment="Bottom">
                                                <Path.Fill>
                                                    <DrawingBrush TileMode="Tile" Viewbox="0,0,3,3" Viewport="0,0,3,3" ViewportUnits="Absolute" ViewboxUnits="Absolute">
                                                        <DrawingBrush.Drawing>
                                                            <DrawingGroup>
                                                                <GeometryDrawing Geometry="M0,0L2,0 2,2 0,2z">
                                                                    <GeometryDrawing.Brush>
                                                                        <LinearGradientBrush EndPoint="1,0.75" StartPoint="0,0.25">
                                                                            <GradientStop Color="#FF2B2B2B" Offset="0.3"/>
                                                                            <GradientStop Color="#FFBBC5D7" Offset="0.75"/>
                                                                            <GradientStop Color="#FF6D83A9" Offset="1"/>
                                                                        </LinearGradientBrush>
                                                                    </GeometryDrawing.Brush>
                                                                </GeometryDrawing>
                                                            </DrawingGroup>
                                                        </DrawingBrush.Drawing>
                                                    </DrawingBrush>
                                                </Path.Fill>
                                            </Path>
                                        </Grid>
                                    </ControlTemplate>
                                </ResizeGrip.Template>
                            </ResizeGrip>
                        </Grid>
                    </Border>
                </ControlTemplate>
            </Setter.Value>
        </Setter>
    </Style>

这里明明设置了ResizeGrip的Cursor="Cross"，但是运行起来就是没有任何效果

**Comment by tpxxn** [comment]
`<Style x:Key="WindowStyle" TargetType="{x:Type Window}">
        <Setter Property="Foreground" Value="{DynamicResource {x:Static SystemColors.WindowTextBrushKey}}"/>
        <Setter Property="Background" Value="{DynamicResource {x:Static SystemColors.WindowBrushKey}}"/>
        <Setter Property="Template">
            <Setter.Value>
                <ControlTemplate TargetType="{x:Type Window}">
                    <Border BorderBrush="{TemplateBinding BorderBrush}" BorderThickness="{TemplateBinding BorderThickness}" Background="{TemplateBinding Background}">
                        <Grid>
                            <AdornerDecorator>
                                <ContentPresenter ContentTemplate="{TemplateBinding ContentTemplate}" Content="{TemplateBinding Content}" ContentStringFormat="{TemplateBinding ContentStringFormat}"/>
                            </AdornerDecorator>
                            <ResizeGrip Cursor="Cross" x:Name="WindowResizeGrip" HorizontalAlignment="Right" IsTabStop="False" Visibility="Visible" VerticalAlignment="Bottom" Margin="0,0,2,2">
                                <ResizeGrip.Template>
                                    <ControlTemplate TargetType="{x:Type ResizeGrip}">
                                        <Grid Background="{TemplateBinding Background}" SnapsToDevicePixels="True">
                                            <Path Data="M9,0L11,0 11,11 0,11 0,9 3,9 3,6 6,6 6,3 9,3z" HorizontalAlignment="Right" Margin="0,0,2,2" VerticalAlignment="Bottom">
                                                <Path.Fill>
                                                    <DrawingBrush TileMode="Tile" Viewbox="0,0,3,3" Viewport="0,0,3,3" ViewportUnits="Absolute" ViewboxUnits="Absolute">
                                                        <DrawingBrush.Drawing>
                                                            <DrawingGroup>
                                                                <GeometryDrawing Geometry="M0,0L2,0 2,2 0,2z">
                                                                    <GeometryDrawing.Brush>
                                                                        <LinearGradientBrush EndPoint="1,0.75" StartPoint="0,0.25">
                                                                            <GradientStop Color="#FF2B2B2B" Offset="0.3"/>
                                                                            <GradientStop Color="#FFBBC5D7" Offset="0.75"/>
                                                                            <GradientStop Color="#FF6D83A9" Offset="1"/>
                                                                        </LinearGradientBrush>
                                                                    </GeometryDrawing.Brush>
                                                                </GeometryDrawing>
                                                            </DrawingGroup>
                                                        </DrawingBrush.Drawing>
                                                    </DrawingBrush>
                                                </Path.Fill>
                                            </Path>
                                        </Grid>
                                    </ControlTemplate>
                                </ResizeGrip.Template>
                            </ResizeGrip>
                        </Grid>
                    </Border>
                </ControlTemplate>
            </Setter.Value>
        </Setter>
    </Style>`

这里明明设置了ResizeGrip的Cursor="Cross"，但是运行起来却没有任何效果，百思不得其解啊
