### ISSUE TITLE
为啥不用html5+javascript?

### ISSUE THREAD

**Issue by houxieyu** [tpxxn/JiHuangBaiKeCSharp#5]
可执行文件还得下载才能打开，兼容性也不好，用htm+js做成网页，手机端都能看

**Comment by tpxxn** [comment]
因为，不会呀~

**Comment by houxieyu** [comment]
桌面程序写成这样已经很屌了，有没有做编辑器？

**Comment by houxieyu** [comment]
做一个服务器和客户端编辑器，可以让很多人一起维护资料，专人负责审核就好了，这样比你自己维护快很多。

**Comment by tpxxn** [comment]
我要是会h5+js大概就做这个了....可是现在在写UWP版本的，毕业论文就是这个，而且网页版wiki也有中文的呀
